name: pokedex

packages:
  - packages/**

scripts:
  analyze:
    exec: dart analyze .
    description: Analyze the project's Dart code.
  build_runner:
    run: melos exec --depends-on="build_runner" dart run build_runner build --delete-conflicting-outputs
    description: Generate code
    