name: 'pokedex'
description: Flutter app example tthat consumes PokeApi
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.2.0
  bloc: ^8.1.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  injectable: ^2.1.1
  intl: any
  lottie: ^2.3.2
  shared_preferences: ^2.1.1
  cached_network_image: ^3.2.3
  google_fonts: ^4.0.4
  pokedex_api:
    path: packages/pokedex_api
  dio_cache_interceptor: ^3.4.2

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    # - assets/icons/
    - assets/images/pokemon_type/
    - assets/lottie/