name: pokedex_api
description: Pokedex API
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.4
  freezed: ^2.3.4
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  retrofit_generator: ^7.0.1
  test: ^1.19.2
  very_good_analysis: ^5.0.0

dependencies:
  dio: ^5.2.0
  dio_cache_interceptor: ^3.4.2
  retrofit: ^4.0.1
